export const SEND_OTP = "SEND_OTP";

export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAILUR = "VERIFY_FAILUR";
export const VERIFY_INIT = "VERIFY_INIT";

export const USERLOGIN_SUCCESS = "USERLOGIN_SUCCESS";

export const DASUSERLOGIN = "DASHBOARD";
