export const SEND_OTP = "SEND_OTP";

export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAILUR = "VERIFY_FAILUR";
export const VERIFY_INIT = "VERIFY_INIT";

export const USERLOGIN_SUCCESS = "USERLOGIN_SUCCESS";
export const USERLOGIN_FAILUR = "USERLOGIN_FAILUR";
export const USERLOGIN_INIT = "USERLOGIN_INIT";
export const EYE = "EYE";

export const DASUSERLOGIN = "DASHBOARD";
